### ISSUE TITLE
get channel method failed

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#6] opened 2016-02-26 18:53 UTC
Hi James,

I get some method failed when using pyasdf to read in the `synthetic.h5` file.
```
In [17]: staxml = ds.waveforms.II_AAK.coordinates 
  File "<string>", line unknown
XMLSyntaxError: Extra content at the end of the document, line 1, column 1405


In [18]: staxml = ds.waveforms.II_AAK.coordinates()
  File "<string>", line unknown
XMLSyntaxError: Extra content at the end of the document, line 1, column 1405
```

The  other method also fails:
```
In [20]: staxml = ds.waveforms.II_AAK.coordinates
  File "<string>", line unknown
XMLSyntaxError: Extra content at the end of the document, line 1, column 1405


In [21]: staxml = ds.waveforms.II_AAK.coordinates()
  File "<string>", line unknown
XMLSyntaxError: Extra content at the end of the document, line 1, column 1405
```

Could you check you output file to check if this works?

**Comment by jas11** [comment] 2016-02-26 19:05
I confirm this error. I'm looking into it.

**Comment by jas11** [comment] 2016-02-26 23:23
It seems to be due to the length of the stationxml (hardcoded) which was modified when I changed the URL and asdf-library module stuff. I'm testing now and will uploaded the changes once I've confirmed it's working.

**Comment by jas11** [comment] 2016-02-27 17:13
I've confirmed it's due to the length. The issue is that the elevation, depth, and other station metadata are not consistent in length between different stations. I'm going to convert and force the length ot be the same. Thanks for catching this!

**Comment by jas11** [comment] 2016-02-27 23:37
Latest commit fixes this problem so I'm closing the issue.

**Closed by jas11** 2016-02-27 23:37 UTC

**Comment by wjlei1990** [comment] 2016-02-28 01:46
Hi James,

After generate the adjoint source file, I can't get the adjoint solver running. The adjoint reader is giving me some error messeages. I have put my specfem and all related data at:
```
/lustre/atlas/proj-shared/geo111/Wenjie/James/specfem3d_globe
```

To get my stuff running, you do need to change one line in src/specfem3D/read_adjoint_sources_ASDF.f90.

```
  call ASDF_read_partial_waveform_f(current_asdf_handle, "AuxiliaryData/AdjointSources/"//&
        trim(adj_source_name) // C_NULL_CHAR, offset, nsamples, adj_source, ier)

```

**Comment by jas11** [comment] 2016-02-28 02:37
Please open a new issue since this is not related to the original issue.

**Comment by jas11** [comment] 2016-02-28 02:39
I went ahead and opened it myself.
